#!/usr/bin/env python3
"""Generate docs/coverage/*.md + docs/VERIFICATION_REPORT.md from the coverage JSON."""
import json, re, os, glob
from collections import Counter, OrderedDict

REPO = '/home/user/Holy-Grills-'
FE = os.path.join(REPO, 'holy-grills-frontend/src')
OUT = os.path.join(REPO, 'docs/coverage')
os.makedirs(OUT, exist_ok=True)

d = json.load(open('/tmp/coverage.json'))
R, C = d['routes'], d['calls']

def rel(p):
    return p.replace(REPO, '')

# ---------------------------------------------------------------- FE -> Flask
lines = ["# Frontend → Flask coverage",
         "",
         "Every `apiClient.*` call in `src/lib/liveApi.ts` plus every relative `fetch('/api/…')`,",
         "matched against the Flask blueprints (paths include the blueprint `url_prefix`).",
         "Generated by `tools/coverage_matrix.py` — regenerate after route or client changes.",
         "",
         "| # | FE call (file:line) | Method | URL | Flask handler (file:line) | Auth | Status |",
         "|---|---|---|---|---|---|---|"]
for i, (loc, http, path, handler, status) in enumerate(C, 1):
    auth = ''
    m = re.search(r'\(auth: ([^)]*)\)', handler)
    if m:
        auth = m.group(1)
        handler = handler[:m.start()].strip()
    lines.append(f"| {i} | `{rel(loc)}` | {http} | `{path}` | {('`' + rel(handler) + '`') if handler and handler != '— (relative call, not via apiClient)' else handler} | {auth or '—'} | {status} |")
open(os.path.join(OUT, 'FRONTEND_TO_FLASK.md'), 'w').write('\n'.join(lines) + '\n')

# ---------------------------------------------------------------- Flask -> FE
def route_regex(route):
    out, i = '', 0
    for m in re.finditer(r"<[^>]+>", route):
        out += re.escape(route[i:m.start()]) + r"[^/]+"
        i = m.end()
    out += re.escape(route[i:])
    return re.compile('^' + out.rstrip('/') + '/?$')

fe = []
for loc, http, path, handler, status in C:
    if status == '404 / orphaned' or http == '(fetch)':
        continue
    p = re.sub(r'\$\{[^}]*\}', 'X', path)
    if not p.startswith('/api'):
        p = '/api' + p
    fe.append((http, p, loc))

lines = ["# Flask → Frontend coverage",
         "",
         "Every registered Flask route, and the frontend call site that reaches it.",
         "`unused (dead from the FE)` = no call site in this frontend; the route may still serve",
         "webhooks, the admin tooling, mobile clients or tests — check before deleting.",
         "",
         "| # | Flask route (file:line) | Method | Auth | FE caller (file:line) | Status |",
         "|---|---|---|---|---|---|"]
used = unused = 0
for i, (meths, path, loc, auth) in enumerate(R, 1):
    rx = route_regex(path)
    callers = [c for c in fe if c[0] in meths and rx.match(c[1])]
    if callers:
        used += 1
        caller = '<br>'.join(f"`{rel(c[2])}`" for c in callers[:3])
        status = 'correct'
    else:
        unused += 1
        caller = '—'
        status = 'unused (dead from the FE)'
    lines.append(f"| {i} | `{rel(loc)}` | {','.join(meths)} | {','.join(auth) or 'public'} | {caller} | {status} |")
open(os.path.join(OUT, 'FLASK_TO_FRONTEND.md'), 'w').write('\n'.join(lines) + '\n')

# ------------------------------------------------ admin sections -> endpoints
liveapi = open(os.path.join(FE, 'lib/liveApi.ts')).read()
method_url = {}
ns = None
for line in liveapi.split('\n'):
    m = re.match(r"\s*const (\w+) = \{", line)
    if m:
        ns = m.group(1)
        continue
    m = re.search(r"async (\w+)\([^)]*\)\s*\{\s*return\s+apiClient\.(get|post|patch|delete|put)\(\s*[`'\"]([^`'\"]+)", line)
    if m and ns:
        method_url[f"{ns}.{m.group(1)}"] = (m.group(2).upper(), m.group(3))
    m = re.search(r"async (\w+)\([^)]*\)\s*\{[^}]*?apiClient\.(get|post|patch|delete|put)\(\s*[`'\"]([^`'\"]+)", line)
    if m and ns:
        method_url.setdefault(f"{ns}.{m.group(1)}", (m.group(2).upper(), m.group(3)))

guard_by_url = []
for meths, path, loc, auth in R:
    guard_by_url.append((route_regex(path), meths, auth, loc))

admin_sections = OrderedDict()
for m in re.finditer(r"case '([\w]+)':\s*return <(\w+)", open(os.path.join(FE, 'pages/Admin.tsx')).read()):
    admin_sections[m.group(1)] = m.group(2)

rows = []
for section, comp in admin_sections.items():
    fp = os.path.join(FE, f'components/admin/{comp}.tsx')
    if not os.path.exists(fp):
        cands = glob.glob(os.path.join(FE, 'components/admin/**/', comp + '.tsx'), recursive=True)
        fp = cands[0] if cands else None
    if not fp:
        rows.append((section, comp, '—', 0, 0, 'component file not found'))
        continue
    src = open(fp).read()
    urls = []
    for m in re.finditer(r"(?:liveApi|mockApi)\.(\w+)\.(\w+)\(", src):
        k = f"{m.group(1)}.{m.group(2)}"
        if k in method_url:
            urls.append(method_url[k])
    uniq = sorted(set(urls))
    guarded = unguarded = noroute = 0
    for meth, path in uniq:
        call_path = re.sub(r'\$\{[^}]*\}', 'X', '/api' + path)
        hit = next((auth for rx, meths, auth, loc in guard_by_url
                    if meth in meths and rx.match(call_path)), None)
        if hit:
            guarded += 1
        elif any(rx.match(call_path) for rx, meths, auth, loc in guard_by_url):
            unguarded += 1          # route exists but carries no guard
        else:
            noroute += 1            # no such route (known contract gap)
    note = []
    if noroute: note.append(f'{noroute} no-route')
    if unguarded: note.append(f'{unguarded} public-by-design')
    rows.append((section, comp, len(uniq), guarded, unguarded, ' / '.join(note)))

summary = {
    'flask_routes': len(R),
    'guarded': sum(1 for r in R if r[3]),
    'public': sum(1 for r in R if not r[3]),
    'fe_calls': len(C),
    'fe_correct': sum(1 for c in C if c[4] == 'correct'),
    'fe_404': sum(1 for c in C if c[4] == '404 / orphaned'),
    'fe_orphan': sum(1 for c in C if c[4] == 'ORPHAN-TBC'),
    'routes_used': used,
    'routes_unused': unused,
    'admin_routes': sum(1 for r in R if r[1].startswith('/api/admin')),
    'admin_routes_guarded': sum(1 for r in R if r[1].startswith('/api/admin') and r[3]),
}

lines = ["# Verification report — full-stack coverage (Base44-free build)",
         "",
         "Static matrix generated from both codebases (`docs/coverage/*`).",
         "Live checks that need the real backend and a real login are marked in §5.",
         "",
         "## 1. Base44 removal — done",
         "",
         "| Item | Resolution |",
         "|---|---|",
         "| `@base44/sdk` imports (`api/base44Client`, `lib/AuthContext`, `components/ProtectedRoute`, `lib/analytics`) | **Deleted** — all four were unreachable: `AuthContext`'s only consumer was `ProtectedRoute`, which had zero importers |",
         "| `@base44/vite-plugin` | **Removed** from `vite.config.ts` + `package.json`; the `@ → src` alias it injected is now declared explicitly (`resolve.alias`) |",
         "| `base44.auth.me()` in `lib/PageNotFound.tsx` | **Swapped** to `liveApi.auth.me()` → Flask `GET /api/auth/me` |",
         "| `media.base44.com` image URLs (`FlameMark`, `lib/mascots`, `offline.html`, `ui/image.tsx`) | **Kept** — asset CDN, removing them breaks rendering |",
         "| `appParams` (`VITE_BASE44_*`) | **Kept** — only `OAuthConsent` still reads it, for MCP endpoints that have **no Flask route** (see §4 stop-and-ask) |",
         "| `app/config.py` CORS origin `…base44.app` | **Kept** — backend-side; removing may break a deployed origin |",
         "",
         f"Bundle impact: main chunk **1,353.81 kB → 1,222.40 kB** (−131.4 kB / −9.7%), gzip **373.98 → 330.11 kB** (−43.9 kB / −11.7%).",
         "",
         "## 2. Coverage summary",
         "",
         f"- Flask routes registered: **{summary['flask_routes']}** ({summary['guarded']} guarded, {summary['public']} public)",
         f"- Frontend calls: **{summary['fe_calls']}** — {summary['fe_correct']} correct, {summary['fe_404']} with no Flask route, {summary['fe_orphan']} MCP orphans",
         f"- Routes with a frontend caller: **{summary['routes_used']}**; with none: **{summary['routes_unused']}**",
         f"- `/api/admin*` routes: **{summary['admin_routes']}**, guarded **{summary['admin_routes_guarded']}/{summary['admin_routes']}**",
         "",
         "## 3. Frontend → Flask: the 8 calls with no route (stop-and-ask list)",
         "",
         "| FE call (file:line) | Flask replacement? |",
         "|---|---|",
         "| `POST /api/orders/:id/resend-tracking` (`liveApi.ts:178`) | none — no email/rate-limit implementation server-side |",
         "| `POST /api/free-sides/redeem` (`liveApi.ts:309`) | backend replaced it with cart-stage `POST /api/free-sides/select` |",
         "| `GET /api/items/archived` (`liveApi.ts:626`) | none — archived rows are filtered out of `GET /menu/items` entirely |",
         "| `POST /api/admin/reviews/:id/promote` (`liveApi.ts:1063`) | none — only `GET /api/admin/reviews` exists |",
         "| `GET /api/admin/free-credits` (`liveApi.ts:1210`) | none — only the grant/items routes exist |",
         "| `GET /api/admin/exclusive-spin/history` (`liveApi.ts:1224`) | none — closest is the prizes fulfilment queue |",
         "| `GET /api/challenges/:id` (`liveApi.ts:1310`) | none — **no caller anywhere** (dead method, delete candidate) |",
         "| `GET /api/settings` (`liveApi.ts:1346`) | real route is `GET /api/storefront/config/public` (flat map, needs a small mapper) |",
         "",
         "Plus two relative fetches in `pages/OAuthConsent.tsx` (`/api/apps/:appId/mcp/consent-info`, `…/authorize-grant`):",
         "**no Flask route exists.** In the Base44 build these were served by the Base44 platform. Decision needed:",
         "port the MCP consent endpoints into Flask, or retire the page.",
         "",
         "Note: 10 of the 12 contract gaps logged in `docs/PHASE3_CONTRACT_GAPS.md` are now proven by the matrix;",
         "`/api/orders/suggestions` and `PATCH /api/admin/settings/<key>` **do** resolve (they were false alarms).",
         "",
         "## 4. Admin-side read (static)",
         "",
         "Backend: **every** `/api/admin*` route carries a guard (`require_auth` + `require_role`). Unique guards in use: "
         + ', '.join(f"`{k}`×{v}" for k, v in Counter(a for r in R for a in (r[3] or [])).most_common()) + ".",
         "",
         "Frontend: `pages/Admin.tsx` renders an **Access denied** screen and clears the session for any role outside",
         "`admin`/`super_admin`; the check happens **before** any admin component mounts and **before** any admin data is fetched.",
         "Link surfaces are role-conditional (`TopNav` only shows the staff button for staff roles).",
         "",
         "| # | Admin section | Component | Endpoints called | Guarded | Public-by-design | Notes |",
         "|---|---|---|---|---|---|---|",
         "|---|---|---|---|---|---|"]
for i, (section, comp, n, g, u, note) in enumerate(rows, 1):
    lines.append(f"| {i} | `{section}` | `{comp}` | {n} | {g} | {u} | {note} |")
lines += ["",
           "The **public-by-design** column counts endpoints an admin screen calls that carry no guard because the",
           "data is public: `GET /menu/items`, `GET /menu/items/:id`, `GET /menu/items/:id/addons`, `GET /menu/categories`,",
           "`GET /menu/kitchen-capacity`, `GET /hp/tiers`, `GET /health`. Guests hit the same routes, so no admin data is",
           "exposed, and every admin-only write on those screens is guarded. **No unguarded route exists under `/api/admin*`.**",
           "",
           "`AdminMenu`'s archived-items view is the one admin screen whose endpoint does not exist (`GET /items/archived`, §3);",
           "it degrades to an empty list today.",
           "",
           "## 5. What still needs a live browser/backed run (sandbox network is allowlisted)",
           "",
           "| Check | Why it can't run here | How to run |",
           "|---|---|---|",
           "| Login → protected page → admin → logout, both roles | egress blocked: the sandbox reaches only the npm registry | the running dev preview, with a real account |",
           "| Admin/user-side API responses (401/403, no data leak) | same | browser DevTools Network tab |",
           "| Flask endpoint latency, Lighthouse/LCP, Slow-3G skeleton checks | same | Lighthouse against the deployed/preview URL |",
           "",
           "## 6. How to regenerate",
           "",
           "`docs/coverage/` is generated. Re-run `tools/coverage_matrix.py` after blueprint or `liveApi` changes."]
open(os.path.join(REPO, 'docs/VERIFICATION_REPORT.md'), 'w').write('\n'.join(lines) + '\n')

print("summary:", json.dumps(summary, indent=1))
print("admin rows:", len(rows))
print("unguarded endpoints referenced by admin components:", sum(r[4] for r in rows))
